-- MySQL Script generated by MySQL Workbench
-- Sat Aug 14 18:53:22 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema otiosum
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `otiosum` ;

-- -----------------------------------------------------
-- Schema otiosum
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `otiosum` DEFAULT CHARACTER SET utf8 COLLATE utf8_slovenian_ci ;
USE `otiosum` ;

-- -----------------------------------------------------
-- Table `otiosum`.`account_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `otiosum`.`account_type` ;

CREATE TABLE IF NOT EXISTS `otiosum`.`account_type` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'account type ID',
  `code` TINYINT(4) NOT NULL COMMENT 'Differante account types\n0 - Admin\n1 - Moderator',
  `type` VARCHAR(45) NOT NULL COMMENT 'More descriptive name for code',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `code_UNIQUE` (`code` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `type_UNIQUE` (`type` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_slovenian_ci;


-- -----------------------------------------------------
-- Table `otiosum`.`country`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `otiosum`.`country` ;

CREATE TABLE IF NOT EXISTS `otiosum`.`country` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'Country ID',
  `country` VARCHAR(55) NOT NULL COMMENT 'Country name',
  `ISO2` VARCHAR(2) NOT NULL COMMENT 'International country ISO2',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `country_UNIQUE` (`country` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `ISO2_UNIQUE` (`ISO2` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 229
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_slovenian_ci;


-- -----------------------------------------------------
-- Table `otiosum`.`city`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `otiosum`.`city` ;

CREATE TABLE IF NOT EXISTS `otiosum`.`city` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `country_id` INT(11) NOT NULL COMMENT 'Country ID',
  `postal_code` VARCHAR(10) NOT NULL COMMENT 'postal code of the city',
  `city` VARCHAR(60) NOT NULL COMMENT 'The name of the City',
  PRIMARY KEY (`id`, `country_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_city_country1_idx` (`country_id` ASC),
  CONSTRAINT `fk_city_country1`
    FOREIGN KEY (`country_id`)
    REFERENCES `otiosum`.`country` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_slovenian_ci;


-- -----------------------------------------------------
-- Table `otiosum`.`account`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `otiosum`.`account` ;

CREATE TABLE IF NOT EXISTS `otiosum`.`account` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'Account ID',
  `username` VARCHAR(120) NOT NULL COMMENT 'Account username',
  `email` VARCHAR(150) NOT NULL COMMENT 'Account email',
  `password` TEXT NOT NULL COMMENT 'Account hashed password',
  `first_name` VARCHAR(60) NOT NULL COMMENT 'The first name of the user.',
  `last_name` VARCHAR(60) NOT NULL COMMENT 'The last name of the user',
  `address` VARCHAR(75) NOT NULL COMMENT 'Users address',
  `address2` VARCHAR(75) NULL DEFAULT NULL COMMENT 'Users second address',
  `phone_number` VARCHAR(20) NULL DEFAULT NULL COMMENT 'Users phone number',
  `active` BIT(1) NOT NULL DEFAULT b'0' COMMENT 'Checks if account has been activated',
  `token` TEXT NOT NULL COMMENT 'Token ',
  `city_id` INT(11) NOT NULL COMMENT 'City ID',
  `account_type_id` INT(11) NULL DEFAULT NULL COMMENT 'The account type ID',
  `date_created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP() COMMENT 'When account was first created',
  `date_updated` DATETIME NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP() COMMENT 'When account data was last updated',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `token_UNIQUE` USING HASH (`token`),
  INDEX `fk_account_account_type1_idx` (`account_type_id` ASC),
  INDEX `fk_account_city1_idx` (`city_id` ASC),
  CONSTRAINT `fk_account_account_type1`
    FOREIGN KEY (`account_type_id`)
    REFERENCES `otiosum`.`account_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_account_city1`
    FOREIGN KEY (`city_id`)
    REFERENCES `otiosum`.`city` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_slovenian_ci;


-- -----------------------------------------------------
-- Table `otiosum`.`brand`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `otiosum`.`brand` ;

CREATE TABLE IF NOT EXISTS `otiosum`.`brand` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'Brand ID',
  `title` VARCHAR(150) NOT NULL COMMENT 'Name of the brand',
  `image` TEXT NOT NULL COMMENT 'Image of the brand',
  `date_created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP() COMMENT 'The Date when brand has been added/created',
  `date_updated` DATETIME NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP() COMMENT 'Datetime of when the brand was last updated',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 25
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_slovenian_ci
COMMENT = 'Table containing data about a brand';


-- -----------------------------------------------------
-- Table `otiosum`.`category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `otiosum`.`category` ;

CREATE TABLE IF NOT EXISTS `otiosum`.`category` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `category` VARCHAR(75) NOT NULL COMMENT 'Category name',
  `date_created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP() COMMENT 'Date/time of category creation',
  `date_updated` DATETIME NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP() COMMENT 'date/time of last update',
  `parent_id` INT(11) NULL DEFAULT NULL COMMENT 'Parent ID of the subcategory',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_category_category1_idx` (`parent_id` ASC),
  CONSTRAINT `fk_category_category1`
    FOREIGN KEY (`parent_id`)
    REFERENCES `otiosum`.`category` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 13
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_slovenian_ci
COMMENT = 'Table containing differante category';


-- -----------------------------------------------------
-- Table `otiosum`.`delivery_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `otiosum`.`delivery_type` ;

CREATE TABLE IF NOT EXISTS `otiosum`.`delivery_type` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(45) NOT NULL,
  `price` FLOAT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `iddelivery_type_UNIQUE` (`id` ASC),
  UNIQUE INDEX `type_UNIQUE` (`type` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_slovenian_ci;


-- -----------------------------------------------------
-- Table `otiosum`.`product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `otiosum`.`product` ;

CREATE TABLE IF NOT EXISTS `otiosum`.`product` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(150) NOT NULL COMMENT 'Title/name of the product',
  `summary` TINYTEXT NULL DEFAULT NULL COMMENT 'A brief summary of the product',
  `description` TEXT NULL DEFAULT NULL COMMENT 'A more detailed description of the product',
  `sku` VARCHAR(8) NOT NULL COMMENT 'Stock Keeping Unit, Allows for easier stock managment',
  `quantity` SMALLINT(6) NOT NULL COMMENT 'Curent quantity/number of items available\\n',
  `price` FLOAT NOT NULL COMMENT 'The price of the product',
  `date_created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP() COMMENT 'The time and date when the product was created',
  `date_updated` DATETIME NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP() COMMENT 'Time and date when the product was updated',
  `date_published` DATE NULL DEFAULT NULL,
  `brand_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `sku` (`sku` ASC),
  INDEX `fk_product_brand1_idx` (`brand_id` ASC),
  CONSTRAINT `fk_product_brand1`
    FOREIGN KEY (`brand_id`)
    REFERENCES `otiosum`.`brand` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 234
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_slovenian_ci
COMMENT = 'Table that containes information about the product';


-- -----------------------------------------------------
-- Table `otiosum`.`measurement`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `otiosum`.`measurement` ;

CREATE TABLE IF NOT EXISTS `otiosum`.`measurement` (
  `product_id` INT(11) NOT NULL,
  `height` FLOAT NULL DEFAULT NULL COMMENT 'Product height',
  `width` FLOAT NULL DEFAULT NULL COMMENT 'Product width',
  `length` FLOAT NULL DEFAULT NULL COMMENT 'Product lenght',
  `weight` FLOAT NULL DEFAULT NULL COMMENT 'Product weight',
  PRIMARY KEY (`product_id`),
  CONSTRAINT `fk_measurement_product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `otiosum`.`product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_slovenian_ci;


-- -----------------------------------------------------
-- Table `otiosum`.`order_status`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `otiosum`.`order_status` ;

CREATE TABLE IF NOT EXISTS `otiosum`.`order_status` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'id of the order status',
  `code` TINYINT(4) NOT NULL COMMENT 'Differante states the order can be in\\n0 - Ordered\\n1 - Shipped\\n2 - Delivered\\n3 - Unable to deliver\\n4 - Canceled',
  `status` VARCHAR(45) NOT NULL COMMENT 'Character name for the status code\\n(Ordered - 1,\\nShipped - 2,\\nDelivered - 3,\\nUnable to deliver - 4,\\nCancelled - 5)',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `code_UNIQUE` (`code` ASC),
  UNIQUE INDEX `status_UNIQUE` (`status` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_slovenian_ci;


-- -----------------------------------------------------
-- Table `otiosum`.`payment_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `otiosum`.`payment_type` ;

CREATE TABLE IF NOT EXISTS `otiosum`.`payment_type` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'The payment_type ID',
  `code` TINYINT(4) NOT NULL COMMENT 'The code for payment_type',
  `type` VARCHAR(45) NOT NULL COMMENT 'The description for the payment type (Cash - 1, Credit Card - 2, Transfer - 3)',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `code_UNIQUE` (`code` ASC),
  UNIQUE INDEX `type_UNIQUE` (`type` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_slovenian_ci
COMMENT = '	';


-- -----------------------------------------------------
-- Table `otiosum`.`order`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `otiosum`.`order` ;

CREATE TABLE IF NOT EXISTS `otiosum`.`order` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'The ID of the order',
  `total` FLOAT NOT NULL COMMENT 'The total SUM of all the items in the order',
  `date_created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP() COMMENT 'The DATE/TIME of when the order has been created',
  `date_updated` DATETIME NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP() COMMENT 'The last time the order has been updated',
  `account_id` INT(11) NOT NULL COMMENT 'The account ID who created the order',
  `order_status_id` INT(11) NULL DEFAULT NULL COMMENT 'The current order status',
  `payment_type_id` INT(11) NOT NULL,
  `delivery_type_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_order_account1_idx` (`account_id` ASC),
  INDEX `fk_order_order_status1_idx` (`order_status_id` ASC),
  INDEX `fk_order_payment_type1_idx` (`payment_type_id` ASC),
  INDEX `fk_order_delivery_type1_idx` (`delivery_type_id` ASC),
  CONSTRAINT `fk_order_account1`
    FOREIGN KEY (`account_id`)
    REFERENCES `otiosum`.`account` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_delivery_type1`
    FOREIGN KEY (`delivery_type_id`)
    REFERENCES `otiosum`.`delivery_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_order_status1`
    FOREIGN KEY (`order_status_id`)
    REFERENCES `otiosum`.`order_status` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_payment_type1`
    FOREIGN KEY (`payment_type_id`)
    REFERENCES `otiosum`.`payment_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 40
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_slovenian_ci;


-- -----------------------------------------------------
-- Table `otiosum`.`order_item`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `otiosum`.`order_item` ;

CREATE TABLE IF NOT EXISTS `otiosum`.`order_item` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `product_id` INT(11) NOT NULL COMMENT 'The product id ',
  `title` VARCHAR(150) NOT NULL,
  `sku` VARCHAR(8) NOT NULL,
  `quantity` INT(11) NOT NULL COMMENT 'The quantity of the product item ',
  `price` FLOAT NOT NULL COMMENT 'Price of one item',
  `total` FLOAT NOT NULL COMMENT 'Total price of the selected product (price*quantity)',
  `date_created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP() COMMENT 'The creation date for the order_item',
  `date_updated` DATETIME NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP() COMMENT 'The last time the order_item has been changed',
  `order_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idorder_item_UNIQUE` (`id` ASC),
  INDEX `fk_order_item_product1_idx` (`product_id` ASC),
  INDEX `fk_order_item_order1_idx` (`order_id` ASC),
  CONSTRAINT `fk_order_item_order1`
    FOREIGN KEY (`order_id`)
    REFERENCES `otiosum`.`order` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_item_product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `otiosum`.`product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 97
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_slovenian_ci;


-- -----------------------------------------------------
-- Table `otiosum`.`product_category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `otiosum`.`product_category` ;

CREATE TABLE IF NOT EXISTS `otiosum`.`product_category` (
  `product_id` INT(11) NOT NULL,
  `category_id` INT(11) NOT NULL,
  PRIMARY KEY (`product_id`, `category_id`),
  INDEX `fk_product_category_category1_idx` (`category_id` ASC),
  INDEX `fk_product_category_product1_idx` (`product_id` ASC),
  CONSTRAINT `fk_product_category_category1`
    FOREIGN KEY (`category_id`)
    REFERENCES `otiosum`.`category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_product_category_product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `otiosum`.`product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_slovenian_ci
COMMENT = 'Connecting table for multiple-multiple relationship between product and category';


-- -----------------------------------------------------
-- Table `otiosum`.`product_image`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `otiosum`.`product_image` ;

CREATE TABLE IF NOT EXISTS `otiosum`.`product_image` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'Image id',
  `caption` VARCHAR(200) NOT NULL COMMENT 'Caption for image in case of inproper image loading',
  `image` TEXT NOT NULL COMMENT 'The image',
  `date_created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP() COMMENT 'Date/time when image was created',
  `date_updated` DATETIME NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP() COMMENT 'date/time when image was updated',
  `product_id` INT(11) NOT NULL COMMENT 'Id of the product to whom the image belongs',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_product_image_product_idx` (`product_id` ASC),
  CONSTRAINT `fk_product_image_product`
    FOREIGN KEY (`product_id`)
    REFERENCES `otiosum`.`product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 100
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_slovenian_ci
COMMENT = 'Table containing image of a product';


-- -----------------------------------------------------
-- Table `otiosum`.`sale`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `otiosum`.`sale` ;

CREATE TABLE IF NOT EXISTS `otiosum`.`sale` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'The sales ID',
  `date_start` DATE NOT NULL COMMENT 'Date and Time of the Sales start',
  `date_end` DATE NOT NULL COMMENT 'Date and time of the end of Sale',
  `discount` INT(11) NOT NULL COMMENT 'The discount on the sale',
  `date_created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP() COMMENT 'Datetime of the creation of the sale',
  `date_updated` DATETIME NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP() COMMENT 'Datetime of the sales update',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 37
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_slovenian_ci;


-- -----------------------------------------------------
-- Table `otiosum`.`product_sale`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `otiosum`.`product_sale` ;

CREATE TABLE IF NOT EXISTS `otiosum`.`product_sale` (
  `product_id` INT(11) NOT NULL,
  `sale_id` INT(11) NOT NULL,
  PRIMARY KEY (`product_id`, `sale_id`),
  INDEX `fk_product_sale_product1_idx` (`product_id` ASC),
  INDEX `fk_product_sale_sale1_idx` (`sale_id` ASC),
  CONSTRAINT `fk_product_sale_product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `otiosum`.`product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_product_sale_sale1`
    FOREIGN KEY (`sale_id`)
    REFERENCES `otiosum`.`sale` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_slovenian_ci;


-- -----------------------------------------------------
-- Table `otiosum`.`review`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `otiosum`.`review` ;

CREATE TABLE IF NOT EXISTS `otiosum`.`review` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'ID of the review',
  `comment` TINYTEXT NOT NULL COMMENT 'The contents of the review',
  `rating` TINYINT(4) NULL DEFAULT NULL COMMENT 'A numerical value of the rating from 0-5',
  `date_created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP() COMMENT 'The date and time when the review has been created',
  `date_updated` DATETIME NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP() COMMENT 'The date and time of when the review has been changed/updated',
  `account_id` INT(11) NOT NULL COMMENT 'The ID of the account who wrote the review',
  `product_id` INT(11) NOT NULL COMMENT 'The ID of the product to whom the review ',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_review_account1_idx` (`account_id` ASC),
  INDEX `fk_review_product1_idx` (`product_id` ASC),
  CONSTRAINT `fk_review_account1`
    FOREIGN KEY (`account_id`)
    REFERENCES `otiosum`.`account` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_review_product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `otiosum`.`product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 34
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_slovenian_ci;


-- -----------------------------------------------------
-- Table `otiosum`.`security`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `otiosum`.`security` ;

CREATE TABLE IF NOT EXISTS `otiosum`.`security` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'The security ID',
  `date_registered` DATETIME NOT NULL COMMENT 'The date/time of when the user has activated the account',
  `first_loggin` DATETIME NULL DEFAULT NULL COMMENT 'The date/time the user has first loged in',
  `last_loggin` DATETIME NULL DEFAULT NULL COMMENT 'The date/time of the last user login',
  `account_id` INT(11) NOT NULL COMMENT 'The account',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `account_id_UNIQUE` (`account_id` ASC),
  INDEX `fk_security_account1_idx` (`account_id` ASC),
  CONSTRAINT `fk_security_account1`
    FOREIGN KEY (`account_id`)
    REFERENCES `otiosum`.`account` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_slovenian_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `otiosum`.`account_type`
-- -----------------------------------------------------
START TRANSACTION;
USE `otiosum`;
INSERT INTO `otiosum`.`account_type` (`id`, `code`, `type`) VALUES (1, 1, 'Admin');
INSERT INTO `otiosum`.`account_type` (`id`, `code`, `type`) VALUES (2, 2, 'Moderator');

COMMIT;


-- -----------------------------------------------------
-- Data for table `otiosum`.`country`
-- -----------------------------------------------------
START TRANSACTION;
USE `otiosum`;
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (1, 'Afghanistan', 'AF');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (2, 'Albania', 'AL');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (3, 'Algeria', 'DZ');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (4, 'American Samoa', 'AS');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (5, 'Andorra', 'AD');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (6, 'Angola', 'AO');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (7, 'Anguilla', 'AI');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (8, 'Antarctica', 'AQ');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (9, 'Antigua and Barbuda', 'AG');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (10, 'Argentina', 'AR');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (11, 'Armenia', 'AM');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (12, 'Aruba', 'AW');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (13, 'Australia', 'AU');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (14, 'Austria', 'AT');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (15, 'Azerbaijan', 'AZ');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (16, 'Bahamas', 'BS');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (17, 'Bahrain', 'BH');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (18, 'Bangladesh', 'BD');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (19, 'Barbados', 'BB');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (20, 'Belarus', 'BY');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (21, 'Belgium', 'BE');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (22, 'Belize', 'BZ');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (23, 'Benin', 'BJ');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (24, 'Bermuda', 'BM');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (25, 'Bhutan', 'BT');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (26, 'Bosnia and Herzegovina', 'BA');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (27, 'Botswana', 'BW');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (28, 'Bouvet Island', 'BV');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (29, 'Brazil', 'BR');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (30, 'British Indian Ocean Territory', 'IO');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (31, 'Brunei Darussalam', 'BN');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (32, 'Bulgaria', 'BG');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (33, 'Burkina Faso', 'BF');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (34, 'Burundi', 'BI');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (35, 'Cambodia', 'KH');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (36, 'Cameroon', 'CM');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (37, 'Canada', 'CA');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (38, 'Cape Verde', 'CV');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (39, 'Cayman Islands', 'KY');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (40, 'Central African Republic', 'CF');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (41, 'Chad', 'TD');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (42, 'Chile', 'CL');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (43, 'China', 'CN');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (44, 'Christmas Island', 'CX');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (45, 'Cocos (Keeling) Islands', 'CC');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (46, 'Colombia', 'CO');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (47, 'Comoros', 'KM');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (48, 'Congo', 'CG');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (49, 'Cook Islands', 'CK');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (50, 'Costa Rica', 'CR');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (51, 'Croatia', 'HR');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (52, 'Cuba', 'CU');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (53, 'Cyprus', 'CY');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (54, 'Czech Republic', 'CZ');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (55, 'Denmark', 'DK');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (56, 'Djibouti', 'DJ');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (57, 'Dominica', 'DM');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (58, 'Dominican Republic', 'DO');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (59, 'Ecuador', 'EC');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (60, 'Egypt', 'EG');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (61, 'El Salvador', 'SV');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (62, 'Equatorial Guinea', 'GQ');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (63, 'Eritrea', 'ER');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (64, 'Estonia', 'EE');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (65, 'Ethiopia', 'ET');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (66, 'Falkland Islands (Malvinas)', 'FK');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (67, 'Faroe Islands', 'FO');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (68, 'Fiji', 'FJ');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (69, 'Finland', 'FI');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (70, 'France', 'FR');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (71, 'French Guiana', 'GF');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (72, 'French Polynesia', 'PF');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (73, 'French Southern Territories', 'TF');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (74, 'Gabon', 'GA');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (75, 'Gambia', 'GM');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (76, 'Georgia', 'GE');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (77, 'Germany', 'DE');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (78, 'Ghana', 'GH');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (79, 'Gibraltar', 'GI');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (80, 'Greece', 'GR');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (81, 'Greenland', 'GL');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (82, 'Grenada', 'GD');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (83, 'Guadeloupe', 'GP');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (84, 'Guam', 'GU');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (85, 'Guatemala', 'GT');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (86, 'Guernsey', 'GG');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (87, 'Guinea', 'GN');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (88, 'Guinea-Bissau', 'GW');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (89, 'Guyana', 'GY');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (90, 'Haiti', 'HT');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (91, 'Heard Island and McDonald Islands', 'HM');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (92, 'Holy See (Vatican City State)', 'VA');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (93, 'Honduras', 'HN');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (94, 'Hong Kong', 'HK');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (95, 'Hungary', 'HU');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (96, 'Iceland', 'IS');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (97, 'India', 'IN');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (98, 'Indonesia', 'ID');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (99, 'Iraq', 'IQ');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (100, 'Ireland', 'IE');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (101, 'Isle of Man', 'IM');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (102, 'Israel', 'IL');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (103, 'Italy', 'IT');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (104, 'Jamaica', 'JM');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (105, 'Japan', 'JP');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (106, 'Jersey', 'JE');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (107, 'Jordan', 'JO');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (108, 'Kazakhstan', 'KZ');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (109, 'Kenya', 'KE');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (110, 'Kiribati', 'KI');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (111, 'Kuwait', 'KW');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (112, 'Kyrgyzstan', 'KG');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (113, 'Lao Peoples Democratic Republic', 'LA');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (114, 'Latvia', 'LV');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (115, 'Lebanon', 'LB');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (116, 'Lesotho', 'LS');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (117, 'Liberia', 'LR');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (118, 'Libya', 'LY');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (119, 'Liechtenstein', 'LI');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (120, 'Lithuania', 'LT');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (121, 'Luxembourg', 'LU');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (122, 'Macao', 'MO');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (123, 'Madagascar', 'MG');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (124, 'Malawi', 'MW');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (125, 'Malaysia', 'MY');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (126, 'Maldives', 'MV');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (127, 'Mali', 'ML');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (128, 'Malta', 'MT');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (129, 'Marshall Islands', 'MH');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (130, 'Martinique', 'MQ');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (131, 'Mauritania', 'MR');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (132, 'Mauritius', 'MU');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (133, 'Mayotte', 'YT');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (134, 'Mexico', 'MX');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (135, 'Monaco', 'MC');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (136, 'Mongolia', 'MN');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (137, 'Montenegro', 'ME');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (138, 'Montserrat', 'MS');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (139, 'Morocco', 'MA');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (140, 'Mozambique', 'MZ');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (141, 'Myanmar', 'MM');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (142, 'Namibia', 'NA');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (143, 'Nauru', 'NR');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (144, 'Nepal', 'NP');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (145, 'Netherlands', 'NL');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (146, 'New Caledonia', 'NC');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (147, 'New Zealand', 'NZ');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (148, 'Nicaragua', 'NI');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (149, 'Niger', 'NE');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (150, 'Nigeria', 'NG');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (151, 'Niue', 'NU');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (152, 'Norfolk Island', 'NF');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (153, 'Northern Mariana Islands', 'MP');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (154, 'Norway', 'NO');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (155, 'Oman', 'OM');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (156, 'Pakistan', 'PK');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (157, 'Palau', 'PW');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (158, 'Panama', 'PA');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (159, 'Papua New Guinea', 'PG');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (160, 'Paraguay', 'PY');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (161, 'Peru', 'PE');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (162, 'Philippines', 'PH');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (163, 'Pitcairn', 'PN');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (164, 'Poland', 'PL');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (165, 'Portugal', 'PT');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (166, 'Puerto Rico', 'PR');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (167, 'Qatar', 'QA');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (168, 'Romania', 'RO');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (169, 'Russian Federation', 'RU');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (170, 'Rwanda', 'RW');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (171, 'Saint Kitts and Nevis', 'KN');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (172, 'Saint Lucia', 'LC');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (173, 'Saint Martin (French part)', 'MF');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (174, 'Saint Pierre and Miquelon', 'PM');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (175, 'Saint Vincent and the Grenadines', 'VC');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (176, 'Samoa', 'WS');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (177, 'San Marino', 'SM');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (178, 'Sao Tome and Principe', 'ST');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (179, 'Saudi Arabia', 'SA');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (180, 'Senegal', 'SN');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (181, 'Serbia', 'RS');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (182, 'Seychelles', 'SC');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (183, 'Sierra Leone', 'SL');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (184, 'Singapore', 'SG');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (185, 'Sint Maarten (Dutch part)', 'SX');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (186, 'Slovakia', 'SK');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (187, 'Slovenia', 'SI');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (188, 'Solomon Islands', 'SB');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (189, 'Somalia', 'SO');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (190, 'South Africa', 'ZA');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (191, 'South Georgia and the South Sandwich Islands', 'GS');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (192, 'South Sudan', 'SS');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (193, 'Spain', 'ES');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (194, 'Sri Lanka', 'LK');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (195, 'Sudan', 'SD');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (196, 'Suricountry', 'SR');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (197, 'Svalbard and Jan Mayen', 'SJ');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (198, 'Swaziland', 'SZ');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (199, 'Sweden', 'SE');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (200, 'Switzerland', 'CH');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (201, 'Syrian Arab Republic', 'SY');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (202, 'Tajikistan', 'TJ');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (203, 'Thailand', 'TH');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (204, 'Timor-Leste', 'TL');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (205, 'Togo', 'TG');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (206, 'Tokelau', 'TK');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (207, 'Tonga', 'TO');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (208, 'Trinidad and Tobago', 'TT');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (209, 'Tunisia', 'TN');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (210, 'Turkey', 'TR');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (211, 'Turkmenistan', 'TM');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (212, 'Turks and Caicos Islands', 'TC');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (213, 'Tuvalu', 'TV');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (214, 'Uganda', 'UG');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (215, 'Ukraine', 'UA');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (216, 'United Arab Emirates', 'AE');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (217, 'United Kingdom', 'GB');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (218, 'United States', 'US');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (219, 'United States Minor Outlying Islands', 'UM');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (220, 'Uruguay', 'UY');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (221, 'Uzbekistan', 'UZ');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (222, 'Vanuatu', 'VU');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (223, 'Viet Nam', 'VN');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (224, 'Wallis and Futuna', 'WF');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (225, 'Western Sahara', 'EH');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (226, 'Yemen', 'YE');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (227, 'Zambia', 'ZM');
INSERT INTO `otiosum`.`country` (`id`, `country`, `ISO2`) VALUES (228, 'Zimbabwe', 'ZW');

COMMIT;


-- -----------------------------------------------------
-- Data for table `otiosum`.`delivery_type`
-- -----------------------------------------------------
START TRANSACTION;
USE `otiosum`;
INSERT INTO `otiosum`.`delivery_type` (`id`, `type`, `price`) VALUES (1, 'Osebni prevzem', 0);
INSERT INTO `otiosum`.`delivery_type` (`id`, `type`, `price`) VALUES (2, 'Standardna dostava', 5.95);
INSERT INTO `otiosum`.`delivery_type` (`id`, `type`, `price`) VALUES (3, 'Prednostna dostava', 7.95);

COMMIT;


-- -----------------------------------------------------
-- Data for table `otiosum`.`order_status`
-- -----------------------------------------------------
START TRANSACTION;
USE `otiosum`;
INSERT INTO `otiosum`.`order_status` (`id`, `code`, `status`) VALUES (1, 1, 'Naročeno');
INSERT INTO `otiosum`.`order_status` (`id`, `code`, `status`) VALUES (2, 2, 'Odposlano');
INSERT INTO `otiosum`.`order_status` (`id`, `code`, `status`) VALUES (3, 3, 'Dostavljeno');
INSERT INTO `otiosum`.`order_status` (`id`, `code`, `status`) VALUES (4, 4, 'Ne moremo dostaviti');
INSERT INTO `otiosum`.`order_status` (`id`, `code`, `status`) VALUES (5, 5, 'Preklicano');

COMMIT;


-- -----------------------------------------------------
-- Data for table `otiosum`.`payment_type`
-- -----------------------------------------------------
START TRANSACTION;
USE `otiosum`;
INSERT INTO `otiosum`.`payment_type` (`id`, `code`, `type`) VALUES (1, 1, 'Gotovina');
INSERT INTO `otiosum`.`payment_type` (`id`, `code`, `type`) VALUES (2, 2, 'Kreditna kartica');
INSERT INTO `otiosum`.`payment_type` (`id`, `code`, `type`) VALUES (3, 3, 'Predračun');

COMMIT;

